name: Demo

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

jobs:
  demo:
    if: github.event_name == 'pull_request'
    # if: ${{ github.event.label.name == 'run-benchmark' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Linux
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Do something
        run: |
          sleep 10

  demo_report:
    if: github.event_name == 'pull_request_target'
    # if: ${{ github.event.label.name == 'run-benchmark' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Report
    runs-on: ubuntu-20.04
    steps:
      - name: Find run id of demo and post log URL
        id: demo_id
        uses: actions/github-script@v4
        with:
          script: |
            const { data: thisRun } = await github.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: ${{ github.run_id }},
            })

            const { data: runs } = await github.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: context.workflow,
                event: "pull_request",
              })

            const workflow_runs = runs.workflow_runs;
            workflow_runs.sort((a, b) => b.created_at.localeCompare(a.created_at))
            for (const run of workflow_runs){
                if (thisRun.head_sha == run.head_sha && run.id != thisRun.id){
                    var chosenRun = run;
                    break;
                }
            }
            const { data: jobs } = await github.actions.listJobsForWorkflowRun({
              owner: "jaimergp",
              repo: "comment-pr-fork",
              run_id: chosenRun.id,
            })
            for (const job of jobs.jobs){
              if ( job.conclusion != "skipped" ){
                var thisJob = job;
                break
              }
            }

            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Benchmarks are running! Check [logs here](${chosenRun.repository.html_url}/pull/${{ github.event.number }}/checks?check_run_id=${thisJob.id}).`
            })